# Generated by Django 4.1 on 2022-09-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('WTW', 'Women Top Wear'), ('WBW', 'Women Bottom Wear'), ('MTW', 'Men Top Wear'), ('MBW', 'Men Bottom Wear')], max_length=100),
        ),
    ]
