# Generated by Django 4.1 on 2022-09-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('WTW', 'Women Topwear'), ('WBW', 'Women Bottomwear'), ('MTW', 'Men Topwear'), ('MBW', 'Men Bottomwear')], max_length=100),
        ),
    ]
