# Generated by Django 4.1 on 2022-11-04 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='pin',
        ),
    ]
